[versions]
composeCompiler = "1.4.4"
compose = "1.5.0-alpha01"
composeMaterial3 = "1.1.0-beta02"

kotlin = "1.8.10"
androidGradle = "8.0.0"

coil = "2.3.0"
accompanist = "0.30.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradle" }
android-library = { id = "com.android.library", version.ref = "androidGradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.25.2" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.10" }

[libraries]
compose-animation-core = { module = "androidx.compose.animation:animation-core", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }

androidx-activity = "androidx.activity:activity-compose:1.7.1"
androidx-core = "androidx.core:core-ktx:1.10.0"
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
androidx-test-ext = "androidx.test.ext:junit:1.1.5"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.1"

accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

junit = "junit:junit:4.13.2"
kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4"
